[ClassVersion("1.0.0.0"), FriendlyName("xExchMailboxTransportService")]
class MSFT_xExchMailboxTransportService : OMI_BaseResource
{
    [Key, Description("Exchange server")] String Identity;
    [Required, EmbeddedInstance("MSFT_Credential"), Description("Credentials used to establish a remote PowerShell session to Exchange")] String Credential;
    [Write, Description("Whether it is OK to restart service MSExchangeTransport")] Boolean AllowServiceRestart;
    [Write, Description("The ConnectivityLogEnabled parameter specifies whether the connectivity log is enabled.")] Boolean ConnectivityLogEnabled;
    [Write, Description("The ConnectivityLogMaxAge parameter specifies the maximum age for the connectivity log file.")] String ConnectivityLogMaxAge;
    [Write, Description("The ConnectivityLogMaxDirectorySize parameter specifies the maximum size of all connectivity logs in the connectivity log directory.")] String ConnectivityLogMaxDirectorySize;
    [Write, Description("The ConnectivityLogMaxFileSize parameter specifies the maximum size of each connectivity log file.")] String ConnectivityLogMaxFileSize;
    [Write, Description("The ConnectivityLogPath parameter specifies the default connectivity log directory location.")] String ConnectivityLogPath;
    [Write, Description("The ContentConversionTracingEnabled parameter specifies whether content conversion tracing is enabled.")] Boolean ContentConversionTracingEnabled;
    [Write, Description("The DomainController parameter specifies the domain controller that's used by this cmdlet to read data from or write data to Active Directory.")] String DomainController;
    [Write, Description("The MailboxDeliveryAgentLogEnabled parameter specifies whether the agent log for the Mailbox Transport Delivery service is enabled.")] Boolean MailboxDeliveryAgentLogEnabled;
    [Write, Description("The MailboxDeliveryAgentLogMaxAge parameter specifies the maximum age for the agent log file of the Mailbox Transport Delivery service.")] String MailboxDeliveryAgentLogMaxAge;
    [Write, Description("The MailboxDeliveryAgentLogMaxDirectorySize parameter specifies the maximum size of all Mailbox Transport Delivery service agent logs in the agent log directory.")] String MailboxDeliveryAgentLogMaxDirectorySize;
    [Write, Description("The MailboxDeliveryAgentLogMaxFileSize parameter specifies the maximum size of each agent log file for the Mailbox Transport Delivery service.")] String MailboxDeliveryAgentLogMaxFileSize;
    [Write, Description("The MailboxDeliveryAgentLogPath parameter specifies the default agent log directory location for the Mailbox Transport Delivery service.")] String MailboxDeliveryAgentLogPath;
    [Write, Description("The MailboxDeliveryConnectorMaxInboundConnection parameter specifies the maximum number of inbound connections for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] String MailboxDeliveryConnectorMaxInboundConnection;
    [Write, Description("The MailboxDeliveryConnectorProtocolLoggingLevel parameter enables or disables SMTP protocol logging for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] String MailboxDeliveryConnectorProtocolLoggingLevel;
    [Write, Description("The MailboxDeliveryConnectorSmtpUtf8Enabled parameters or disables email address internationalization (EAI) support for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] Boolean MailboxDeliveryConnectorSMTPUtf8Enabled;
    [Write, Description("The MailboxDeliveryThrottlingLogEnabled parameter specifies whether the mailbox delivery throttling log is enabled.")] Boolean MailboxDeliveryThrottlingLogEnabled;
    [Write, Description("The MailboxDeliveryThrottlingLogMaxAge parameter specifies the maximum age for the mailbox delivery throttling log file.")] String MailboxDeliveryThrottlingLogMaxAge;
    [Write, Description("The MailboxDeliveryThrottlingLogMaxDirectorySize parameter specifies the maximum size of all mailbox delivery throttling logs in the mailbox delivery throttling log directory.")] String MailboxDeliveryThrottlingLogMaxDirectorySize;
    [Write, Description("The MailboxDeliveryThrottlingLogMaxFileSize parameter specifies the maximum size of each mailbox delivery throttling log file.")] String MailboxDeliveryThrottlingLogMaxFileSize;
    [Write, Description("The MailboxDeliveryThrottlingLogPath parameter specifies the default mailbox delivery throttling log directory location.")] String MailboxDeliveryThrottlingLogPath;
    [Write, Description("The MailboxSubmissionAgentLogEnabled parameter specifies whether the agent log is enabled for the Mailbox Transport Submission service.")] Boolean MailboxSubmissionAgentLogEnabled;
    [Write, Description("The MailboxSubmissionAgentLogMaxAge parameter specifies the maximum age for the agent log file of the Mailbox Transport Submission service.")] String MailboxSubmissionAgentLogMaxAge;
    [Write, Description("The MailboxSubmissionAgentLogMaxDirectorySize parameter specifies the maximum size of all Mailbox Transport Submission service agent logs in the agent log directory.")] String MailboxSubmissionAgentLogMaxDirectorySize;
    [Write, Description("The MailboxSubmissionAgentLogMaxFileSize parameter specifies the maximum size of each agent log file for the Mailbox Transport Submission service.")] String MailboxSubmissionAgentLogMaxFileSize;
    [Write, Description("The MailboxSubmissionAgentLogPath parameter specifies the default agent log directory location for the Mailbox Transport Submission service.")] String MailboxSubmissionAgentLogPath;
    [Write, Description("The MaxConcurrentMailboxDeliveries parameter specifies the maximum number of delivery threads that the transport service can have open at the same time to deliver messages to mailboxes.")] SInt32 MaxConcurrentMailboxDeliveries;
    [Write, Description("The MaxConcurrentMailboxSubmissions parameter specifies the maximum number of submission threads that the transport service can have open at the same time to send messages from mailboxes.")] SInt32 MaxConcurrentMailboxSubmissions;
    [Write, Description("The PipelineTracingEnabled parameter specifies whether to enable pipeline tracing.")] Boolean PipelineTracingEnabled;
    [Write, Description("The PipelineTracingPath parameter specifies the location of the pipeline tracing logs.")] String PipelineTracingPath;
    [Write, Description("The PipelineTracingSenderAddress parameter specifies the sender email address that invokes pipeline tracing.")] String PipelineTracingSenderAddress;
    [Write, Description("The ReceiveProtocolLogMaxAge parameter specifies the maximum age of a protocol log file for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] String ReceiveProtocolLogMaxAge;
    [Write, Description("The ReceiveProtocolLogMaxDirectorySize parameter specifies the maximum size of the protocol log directory for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] String ReceiveProtocolLogMaxDirectorySize;
    [Write, Description("The ReceiveProtocolLogMaxFileSize parameter specifies the maximum size of a protocol log file for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] String ReceiveProtocolLogMaxFileSize;
    [Write, Description("The ReceiveProtocolLogPath parameter specifies the location of the protocol log directory for the implicit and invisible mailbox delivery Receive connector in the Mailbox Transport Delivery service.")] String ReceiveProtocolLogPath;
    [Write, Description("The RoutingTableLogMaxAge parameter specifies the maximum routing table log age.")] String RoutingTableLogMaxAge;
    [Write, Description("The RoutingTableLogMaxDirectorySize parameter specifies the maximum size of the routing table log directory.")] String RoutingTableLogMaxDirectorySize;
    [Write, Description("The RoutingTableLogPath parameter specifies the directory location where routing table log files should be stored.")] String RoutingTableLogPath;
    [Write, Description("The SendProtocolLogMaxAge parameter specifies the maximum age of a protocol log file for the implicit and invisible intra-organization Send connector in the Mailbox Transport Submission service.")] String SendProtocolLogMaxAge;
    [Write, Description("The SendProtocolLogMaxDirectorySize parameter specifies the maximum size of the protocol log directory for the implicit and invisible intra-organization Send connector in the Mailbox Transport Submission service.")] String SendProtocolLogMaxDirectorySize;
    [Write, Description("The SendProtocolLogMaxFileSize parameter specifies the maximum size of a protocol log file for the implicit and invisible intra-organization Send connector in the Mailbox Transport Submission service.")] String SendProtocolLogMaxFileSize;
    [Write, Description("The SendProtocolLogPath parameter specifies the location of the protocol log directory for the implicit and invisible intra-organization Send connector in the Mailbox Transport Submission service.")] String SendProtocolLogPath;
};
