
[ClassVersion("1.0.0.0"), FriendlyName("xExchJetstress")]
class MSFT_xExchJetstress : OMI_BaseResource
{
    [Key, Description("Specifies the Type which was defined in the JetstressConfig.xml file. Valid values are Performance, Stress, DatabaseBackup, or SoftRecovery. Defaults to Performance."), ValueMap{"Performance","Stress","DatabaseBackup","SoftRecovery"}, Values{"Performance","Stress","DatabaseBackup","SoftRecovery"}] String Type;
    [Required, Description("The path to the folder where Jetstress is installed, and which contains JetstressCmd.exe")] String JetstressPath;
    [Required, Description("Command line parameters to pass into JetstressCmd.exe")] String JetstressParams;
    [Write, Description("The maximum amount of time that the xExchJetstress resource can run for. Defaults to 4320.")] Uint32 MaxWaitMinutes;
};



