
[ClassVersion("1.0.0.0"), FriendlyName("xExchDatabaseAvailabilityGroupMember")]
class MSFT_xExchDatabaseAvailabilityGroupMember : OMI_BaseResource
{
    [Key] String MailboxServer; //Must be Hostname of Server, not FQDN
    [Required, EmbeddedInstance("MSFT_Credential")] String Credential; //Credentials used to establish a remote Powershell session to Exchange
    [Required] String DAGName; //Name of DAG to add member to
    [Write] String DomainController; //Domain controller to talk to when running Add-DatabaseAvailabilityGroupMember
    [Write] Boolean SkipDagValidation; //Whether SkipDagValidation should be passed to Add-DatabaseAvailabilityGroupMember    
};



