
[ClassVersion("1.0.0.0"), FriendlyName("xExchMaintenanceMode")]
class MSFT_xExchMaintenanceMode : OMI_BaseResource
{
    [Key, Description("Whether the server should be put into Maintenance Mode. When Enabled is set to True, the server will be put in Maintenance Mode. If False, the server will be taken out of Maintenance Mode.")] Boolean Enabled;
    [Required, Description("Credentials used to establish a remote PowerShell session to Exchange"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("When taking a server out of Maintenance Mode, the following components will be set to Active by default: ServerWideOffline, UMCallRouter, HighAvailability, Monitoring, RecoveryActionsEnabled. This parameter specifies an additional list of components to set to Active.")] String AdditionalComponentsToActivate[];
    [Write, Description("The DomainController parameter specifies the fully qualified domain name (FQDN) of the domain controller that writes this configuration change to Active Directory.")] String DomainController;
    [Write, Description("Used when moving databases back to the server after taking the server out of maintenance mode. The MountDialOverride parameter is used to override the auto database mount dial (AutoDatabaseMountDial) setting for the target server and specify an alternate setting. Defaults to None."), ValueMap{"None","Lossless","GoodAvailability","BestAvailability","BestEffort"}, Values{"None","Lossless","GoodAvailability","BestAvailability","BestEffort"}] String MountDialOverride;
    [Write, Description("Whether to move back databases with an Activation Preference of one for this server after taking the server out of Maintenance Mode. Defaults to False.")] Boolean MovePreferredDatabasesBack;
    [Write, Description("Whether components that were set to Inactive by outside Requesters should also be set to Active when exiting Maintenance Mode. Defaults to False.")] Boolean SetInactiveComponentsFromAnyRequesterToActive;
    [Write, Description("Used when moving databases back to the server after taking the server out of maintenance mode. The SkipActiveCopyChecks switch specifies whether to skip checking the current active copy to see if it's currently a seeding source for any passive databases. Defaults to False.")] Boolean SkipActiveCopyChecks;
    [Write, Description("Exchange 2016 Only. Used when moving databases back to the server after taking the server out of maintenance mode. The SkipAllChecks switch specifies whether to skip all checks. This switch is equivalent to specifying all of the individual skip parameters that are available on this cmdlet. Defaults to False.")] Boolean SkipAllChecks;
    [Write, Description("Used when moving databases back to the server after taking the server out of maintenance mode. The SkipClientExperienceChecks switch specifies whether to skip the search catalog (content index) state check to see if the search catalog is healthy and up to date. Defaults to False.")] Boolean SkipClientExperienceChecks;
    [Write, Description("Exchange 2016 Only. Used when moving databases back to the server after taking the server out of maintenance mode. The SkipCpuChecks switch specifies whether to skip the high CPU utilization checks. Defaults to False.")] Boolean SkipCpuChecks;
    [Write, Description("Used when moving databases back to the server after taking the server out of maintenance mode. The SkipHealthChecks switch specifies whether to bypass passive copy health checks. Defaults to False.")] Boolean SkipHealthChecks;
    [Write, Description("Used when moving databases back to the server after taking the server out of maintenance mode. The SkipLagChecks switch specifies whether to allow a copy to be activated that has replay and copy queues outside of the configured criteria. Defaults to False.")] Boolean SkipLagChecks;
    [Write, Description("Used when moving databases back to the server after taking the server out of maintenance mode. The SkipMaximumActiveDatabasesChecks switch specifies whether to skip checking the value of MaximumPreferredActiveDatabases during the best copy and server selection (BCSS) process. Defaults to False.")] Boolean SkipMaximumActiveDatabasesChecks;
    [Write, Description("Exchange 2016 Only. Used when moving databases back to the server after taking the server out of maintenance mode. The SkipMoveSuppressionChecks switch specifies whether to skip the move suppression checks. Defaults to False.")] Boolean SkipMoveSuppressionChecks;
    [Write, Description("Optional string to specify what the server version will be after applying a Cumulative Update. If the server is already at this version, requests to put the server in Maintenance Mode will be ignored. Version should be in the format ##.#.####.#, as in 15.0.1104.5.")] String UpgradedServerVersion;
};

