[ClassVersion("1.0.0.0"), FriendlyName("xExchTransportService")]
class MSFT_xExchTransportService : OMI_BaseResource
{
    [Key] String Identity; //Exchange server
    [Required, EmbeddedInstance("MSFT_Credential")] String Credential; //Credentials used to establish a remote Powershell session to Exchange
    [Write] Boolean AllowServiceRestart; //Whether it is OK to restart service MSExchangeTransport;
    [Write] String ActiveUserStatisticsLogMaxAge;
    [Write] String ActiveUserStatisticsLogMaxDirectorySize;
    [Write] String ActiveUserStatisticsLogMaxFileSize;
    [Write] String ActiveUserStatisticsLogPath;
    [Write] Boolean AgentLogEnabled;
    [Write] String AgentLogMaxAge;
    [Write] String AgentLogMaxDirectorySize;
    [Write] String AgentLogMaxFileSize;
    [Write] String AgentLogPath;
    [Write] Boolean ConnectivityLogEnabled;
    [Write] String ConnectivityLogMaxAge;
    [Write] String ConnectivityLogMaxDirectorySize;
    [Write] String ConnectivityLogMaxFileSize;
    [Write] String ConnectivityLogPath;
    [Write] Boolean ContentConversionTracingEnabled;
    [Write] String DelayNotificationTimeout;
    [Write] Boolean DnsLogEnabled;
    [Write] String DnsLogMaxAge;
    [Write] String DnsLogMaxDirectorySize;
    [Write] String DnsLogMaxFileSize;
    [Write] String DnsLogPath;
    [Write] Boolean ExternalDNSAdapterEnabled;
    [Write] String ExternalDNSAdapterGuid;
    [Write,ValueMap{"Any","UseTcpOnly","UseUdpOnly"}, Values{"Any","UseTcpOnly","UseUdpOnly"}] String ExternalDNSProtocolOption;
    [Write] String ExternalDNSServers[];
    [Write] String ExternalIPAddress;
    [Write] Boolean InternalDNSAdapterEnabled;
    [Write] String InternalDNSAdapterGuid;
    [Write,ValueMap{"Any","UseTcpOnly","UseUdpOnly"}, Values{"Any","UseTcpOnly","UseUdpOnly"}] String InternalDNSProtocolOption;
    [Write] String InternalDNSServers[];
    [Write,ValueMap{"None","Verbose"}, Values{"None","Verbose"}] String IntraOrgConnectorProtocolLoggingLevel;
    [Write] SInt32 IntraOrgConnectorSmtpMaxMessagesPerConnection;
    [Write] Boolean IrmLogEnabled;
    [Write] String IrmLogMaxAge;
    [Write] String IrmLogMaxDirectorySize;
    [Write] String IrmLogMaxFileSize;
    [Write] String IrmLogPath;
    [Write] SInt32 MaxConcurrentMailboxDeliveries;
    [Write] SInt32 MaxConcurrentMailboxSubmissions;
    [Write] SInt32 MaxConnectionRatePerMinute;
    [Write] String MaxOutboundConnections;
    [Write] String MaxPerDomainOutboundConnections;
    [Write] String MessageExpirationTimeout;
    [Write] String MessageRetryInterval;
    [Write] Boolean MessageTrackingLogEnabled;
    [Write] String MessageTrackingLogMaxAge;
    [Write] String MessageTrackingLogMaxDirectorySize;
    [Write] String MessageTrackingLogMaxFileSize;
    [Write] String MessageTrackingLogPath;
    [Write] Boolean MessageTrackingLogSubjectLoggingEnabled;
    [Write] String OutboundConnectionFailureRetryInterval;
    [Write] String PickupDirectoryMaxHeaderSize;
    [Write] SInt32 PickupDirectoryMaxMessagesPerMinute;
    [Write] SInt32 PickupDirectoryMaxRecipientsPerMessage;
    [Write] String PickupDirectoryPath;
    [Write] Boolean PipelineTracingEnabled;
    [Write] String PipelineTracingPath;
    [Write] String PipelineTracingSenderAddress;
    [Write] Boolean PoisonMessageDetectionEnabled;
    [Write] SInt32 PoisonThreshold;
    [Write] String QueueLogMaxAge;
    [Write] String QueueLogMaxDirectorySize;
    [Write] String QueueLogMaxFileSize;
    [Write] String QueueLogPath;
    [Write] String QueueMaxIdleTime;
    [Write] String ReceiveProtocolLogMaxAge;
    [Write] String ReceiveProtocolLogMaxDirectorySize;
    [Write] String ReceiveProtocolLogMaxFileSize;
    [Write] String ReceiveProtocolLogPath;
    [Write] Boolean RecipientValidationCacheEnabled;
    [Write] String ReplayDirectoryPath;
    [Write] String RootDropDirectoryPath;
    [Write] String RoutingTableLogMaxAge;
    [Write] String RoutingTableLogMaxDirectorySize;
    [Write] String RoutingTableLogPath;
    [Write] String SendProtocolLogMaxAge;
    [Write] String SendProtocolLogMaxDirectorySize;
    [Write] String SendProtocolLogMaxFileSize;
    [Write] String SendProtocolLogPath;
    [Write] String ServerStatisticsLogMaxAge;
    [Write] String ServerStatisticsLogMaxDirectorySize;
    [Write] String ServerStatisticsLogMaxFileSize;
    [Write] String ServerStatisticsLogPath;
    [Write] SInt32 TransientFailureRetryCount;
    [Write] String TransientFailureRetryInterval;
    [Write] Boolean UseDowngradedExchangeServerAuth;
};
