[ClassVersion("1.0.0.0"), FriendlyName("xExchFrontendTransportService")]
class MSFT_xExchFrontendTransportService : OMI_BaseResource
{
    [Key, Description("Hostname of the server to configure.")] String Identity;
    [Required, Description("Credentials used to establish a remote PowerShell session to Exchange."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Whether it is OK to restart the MSExchangeFrontEndTransport service after making changes. Defaults to $false.")] Boolean AllowServiceRestart;
    [Write, Description("The AgentLogEnabled parameter specifies whether the agent log is enabled. The default value is $true.")] Boolean AgentLogEnabled;
    [Write, Description("The AgentLogMaxAge parameter specifies the maximum age for the agent log file. Log files older than the specified value are deleted. The default value is 7.00:00:00 or 7 days.")] String AgentLogMaxAge;
    [Write, Description("The AgentLogMaxDirectorySize parameter specifies the maximum size of all agent logs in the agent log directory. When a directory reaches its maximum file size, the server deletes the oldest log files first. The default value is 250 MB.")] String AgentLogMaxDirectorySize;
    [Write, Description("The AgentLogMaxFileSize parameter specifies the maximum size of each agent log file. When a log file reaches its maximum file size, a new log file is created. The default value is 10 MB.")] String AgentLogMaxFileSize;
    [Write, Description("The AgentLogPath parameter specifies the default agent log directory location.")] String AgentLogPath;
    [Write, Description("The AntispamAgentsEnabled parameter specifies whether anti-spam agents are installed on the server specified with the Identity parameter. The default value is $false for the Front End Transport service.")] Boolean AntispamAgentsEnabled;
    [Write, Description("The ConnectivityLogEnabled parameter specifies whether the connectivity log is enabled. The default value is $true.")] Boolean ConnectivityLogEnabled;
    [Write, Description("The ConnectivityLogMaxAge parameter specifies the maximum age for the connectivity log file. Log files older than the specified value are deleted. The default value is 30 days.")] String ConnectivityLogMaxAge;
    [Write, Description("The ConnectivityLogMaxDirectorySize parameter specifies the maximum size of all connectivity logs in the connectivity log directory. When a directory reaches its maximum file size, the server deletes the oldest log files first. The default value is 1000 MB.")] String ConnectivityLogMaxDirectorySize;
    [Write, Description("The ConnectivityLogMaxFileSize parameter specifies the maximum size of each connectivity log file. When a log file reaches its maximum file size, a new log file is created. The default value is 10 MB.")] String ConnectivityLogMaxFileSize;
    [Write, Description("The ConnectivityLogPath parameter specifies the default connectivity log directory location.")] String ConnectivityLogPath;
    [Write, Description("The DnsLogEnabled parameter specifies whether the DNS log is enabled. The default value is $false.")] Boolean DnsLogEnabled;
    [Write, Description("The DnsLogMaxAge parameter specifies the maximum age for the DNS log file. Log files older than the specified value are deleted. The default value is 7.00:00:00 or 7 days.")] String DnsLogMaxAge;
    [Write, Description("The DnsLogMaxDirectorySize parameter specifies the maximum size of all DNS logs in the DNS log directory. When a directory reaches its maximum file size, the server deletes the oldest log files first. The default value is 100 MB.")] String DnsLogMaxDirectorySize;
    [Write, Description("The DnsLogMaxFileSize parameter specifies the maximum size of each DNS log file. When a log file reaches its maximum file size, a new log file is created. The default value is 10 MB.")] String DnsLogMaxFileSize;
    [Write, Description("The DnsLogPath parameter specifies the DNS log directory location. The default value is blank ($null), which indicates no location is configured. If you enable DNS logging, you need to specify a local file path for the DNS log files by using this parameter.")] String DnsLogPath;
    [Write, Description("The ExternalDNSAdapterEnabled parameter specifies one or more Domain Name System (DNS) servers that Exchange uses for external DNS lookups.")] Boolean ExternalDNSAdapterEnabled;
    [Write, Description("The ExternalDNSAdapterGuid parameter specifies the network adapter that has the DNS settings used for DNS lookups of destinations that exist outside the Exchange organization.")] String ExternalDNSAdapterGuid;
    [Write, Description("The ExternalDNSProtocolOption parameter specifies which protocol to use when querying external DNS servers. The valid options for this parameter are Any, UseTcpOnly, and UseUdpOnly. The default value is Any."), ValueMap{"Any","UseTcpOnly","UseUdpOnly"}, Values{"Any","UseTcpOnly","UseUdpOnly"}] String ExternalDNSProtocolOption;
    [Write, Description("The ExternalDNSServers parameter specifies the list of external DNS servers that the server queries when resolving a remote domain. You must separate IP addresses by using commas. The default value is an empty list ({}).")] String ExternalDNSServers[];
    [Write, Description("The ExternalIPAddress parameter specifies the IP address used in the Received message header field for every message that travels through the Front End Transport service.")] String ExternalIPAddress;
    [Write, Description("The InternalDNSAdapterEnabled parameter specifies one or more DNS servers that Exchange uses for internal DNS lookups.")] Boolean InternalDNSAdapterEnabled;
    [Write, Description("The InternalDNSAdapterGuid parameter specifies the network adapter that has the DNS settings used for DNS lookups of servers that exist inside the Exchange organization.")] String InternalDNSAdapterGuid;
    [Write, Description("The InternalDNSProtocolOption parameter specifies which protocol to use when you query internal DNS servers. Valid options for this parameter are Any, UseTcpOnly, or UseUdpOnly. The default value is Any."), ValueMap{"Any","UseTcpOnly","UseUdpOnly"}, Values{"Any","UseTcpOnly","UseUdpOnly"}] String InternalDNSProtocolOption;
    [Write, Description("The InternalDNSServers parameter specifies the list of DNS servers that should be used when resolving a domain name. DNS servers are specified by IP address and are separated by commas. The default value is any empty list ({}).")] String InternalDNSServers[];
    [Write, Description("The IntraOrgConnectorProtocolLoggingLevel parameter enables or disables SMTP protocol logging on the implicit and invisible intra-organization Send connector in the Front End Transport service."), ValueMap{"None","Verbose"}, Values{"None","Verbose"}] String IntraOrgConnectorProtocolLoggingLevel;
    [Write, Description("The MaxConnectionRatePerMinute parameter specifies the maximum rate that connections are allowed to be opened with the transport service.")] SInt32 MaxConnectionRatePerMinute;
    [Write, Description("The ReceiveProtocolLogMaxAge parameter specifies the maximum age of a protocol log file that's shared by all Receive connectors in the Transport service on the server. Log files that are older than the specified value are automatically deleted.")] String ReceiveProtocolLogMaxAge;
    [Write, Description("The ReceiveProtocolLogMaxDirectorySize parameter specifies the maximum size of the protocol log directory that's shared by all Receive connectors in the Front End Transport service on the server. When the maximum directory size is reached, the server deletes the oldest log files first.")] String ReceiveProtocolLogMaxDirectorySize;
    [Write, Description("The ReceiveProtocolLogMaxFileSize parameter specifies the maximum size of a protocol log file that's shared by all Receive connectors in the Front End Transport service on the server. When a log file reaches its maximum file size, a new log file is created.")] String ReceiveProtocolLogMaxFileSize;
    [Write, Description("The ReceiveProtocolLogPath parameter specifies the location of the protocol log directory for all Receive connectors in the Front End Transport service on the server.")] String ReceiveProtocolLogPath;
    [Write, Description("The RoutingTableLogMaxAge parameter specifies the maximum routing table log age. Log files older than the specified value are deleted. The default value is 7 days.")] String RoutingTableLogMaxAge;
    [Write, Description("The RoutingTableLogMaxDirectorySize parameter specifies the maximum size of the routing table log directory. When the maximum directory size is reached, the server deletes the oldest log files first. The default value is 250 MB.")] String RoutingTableLogMaxDirectorySize;
    [Write, Description("The RoutingTableLogPath parameter specifies the directory location where routing table log files should be stored.")] String RoutingTableLogPath;
    [Write, Description("The SendProtocolLogMaxAge parameter specifies the maximum age of a protocol log file that's shared by all Send connectors in the Front End Transport service that have this server configured as a source server. Log files that are older than the specified value are deleted.")] String SendProtocolLogMaxAge;
    [Write, Description("The SendProtocolLogMaxDirectorySize parameter specifies the maximum size of the protocol log directory that's shared by all Send connectors in the Front End Transport service that have this server configured as a source server. When the maximum directory size is reached, the server deletes the oldest log files first.")] String SendProtocolLogMaxDirectorySize;
    [Write, Description("The SendProtocolLogMaxFileSize parameter specifies the maximum size of a protocol log file that's shared by all the Send connectors in the Front End Transport service that have this server configured as a source server. When a log file reaches its maximum file size, a new log file is created.")] String SendProtocolLogMaxFileSize;
    [Write, Description("The SendProtocolLogPath parameter specifies the location of the protocol log directory for all Send connectors in the Front End Transport service that have this server configured as a source server.")] String SendProtocolLogPath;
    [Write, Description("The TransientFailureRetryCount parameter specifies the maximum number of immediate connection retries attempted when the server encounters a connection failure with a remote server. The default value is 6. The valid input range for this parameter is from 0 through 15. When the value of this parameter is set to 0, the server doesn't immediately attempt to retry an unsuccessful connection.")] SInt32 TransientFailureRetryCount;
    [Write, Description("The TransientFailureRetryInterval parameter controls the connection interval between each connection attempt specified by the TransientFailureRetryCount parameter. For the Front End Transport service, the default value of the TransientFailureRetryInterval parameter is 5 minutes.")] String TransientFailureRetryInterval;
};
