
[ClassVersion("1.0.0.0"), FriendlyName("xExchImapSettings")]
class MSFT_xExchImapSettings : OMI_BaseResource
{
    [Key, Description("The IMAP server to configure.")] String Server;
    [Required, Description("Credentials used to establish a remote PowerShell session to Exchange."), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Whether it is OK to restart the IMAP services after making changes. Defaults to $false.")] Boolean AllowServiceRestart;
    [Write, Description("The DomainController parameter specifies the domain controller that's used by this cmdlet to read data from or write data to Active Directory. You identify the domain controller by its fully qualified domain name (FQDN). For example, dc01.contoso.com.")] String DomainController; //Optional Domain Controller to connect to
    [Write, Description("The ExternalConnectionSettings parameter specifies the host name, port, and encryption method that's used by external IMAP4 clients (IMAP4 connections from outside your corporate network).")] String ExternalConnectionSettings[];
    [Write, Description("The LoginType parameter specifies the authentication method for IMAP4 connections."), ValueMap{"PlainTextLogin","PlainTextAuthentication","SecureLogin"}, Values{"PlainTextLogin","PlainTextAuthentication","SecureLogin"}] String LoginType;
    [Write, Description("The X509CertificateName parameter specifies the certificate that's used for encrypting IMAP4 client connections.")] String X509CertificateName;
};
