
[ClassVersion("1.0.0.0"), FriendlyName("xExchMailboxDatabaseCopy")]
class MSFT_xExchMailboxDatabaseCopy : OMI_BaseResource
{
    [Key] String Identity; //Name of database
    [Required, EmbeddedInstance("MSFT_Credential")] String Credential; //Credentials used to establish a remote Powershell session to Exchange
    [Required] String MailboxServer; //Server to add copy to. Should be the host name, not the FQDN.
    [Write] String AdServerSettingsPreferredServer; //An optional domain controller to pass to Set-AdServerSettings -PreferredServer
    [Write] Boolean AllowServiceRestart; //Whether it is OK to restart Information Store after adding copy

    //Remaing props, and some of the above, correspond directly to Add-MailboxDatabaseCopy parameters
    //http://technet.microsoft.com/en-us/library/dd298105(v=exchg.150).aspx
    [Write] Uint32 ActivationPreference; 
    [Write] String DomainController;
    [Write] String ReplayLagTime;
    [Write] Boolean SeedingPostponed;
    [Write] String TruncationLagTime;    
};



