
[ClassVersion("1.0.0.0"), FriendlyName("xExchPopSettings")]
class MSFT_xExchPopSettings : OMI_BaseResource
{
    [Key] String Server; //The POP server to configure
    [Required, EmbeddedInstance("MSFT_Credential")] String Credential; //Credentials used to establish a remote Powershell session to Exchange
    [Write] Boolean AllowServiceRestart; //Whether it is OK to restart the POP services after making changes. Defaults to $false.
    [Write] String DomainController; //Optional Domain Controller to connect to
    [Write, ValueMap{"PlainTextLogin","PlainTextAuthentication","SecureLogin"}, Values{"PlainTextLogin","PlainTextAuthentication","SecureLogin"}] String LoginType; //The LoginType to be used for POP
    [Write] String ExternalConnectionSettings[]; //Specifies the host name, port, and encryption type that Exchange uses when POP3 clients connect to their email from the outside
    [Write] String X509CertificateName; //Specifies the host name in the SSL certificate from the Associated Subject field.
};



