
[ClassVersion("1.0.0.0"), FriendlyName("xExchMailboxServer")]
class MSFT_xExchMailboxServer : OMI_BaseResource
{
    [Key, Description("The Identity parameter specifies the Mailbox server that you want to modify.")] String Identity;
    [Required, Description("Credentials used to establish a remote Powershell session to Exchange"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("The AutoDatabaseMountDial parameter specifies the automatic database mount behavior for a continuous replication environment after a database failover."), ValueMap{"BestAvailability","GoodAvailability","Lossless"}, Values{"BestAvailability","GoodAvailability","Lossless"}] String AutoDatabaseMountDial;
    [Write, Description("The CalendarRepairIntervalEndWindow parameter specifies the number of days into the future to repair calendars. For example, if this parameter is set to 90, the Calendar Repair Assistant repairs calendars on this Mailbox server 90 days from now.")] SInt32 CalendarRepairIntervalEndWindow;
    [Write, Description("The CalendarRepairLogDirectorySizeLimit parameter specifies the size limit for all log files for the Calendar Repair Assistant. After the limit is reached, the oldest files are deleted.")] String CalendarRepairLogDirectorySizeLimit;
    [Write, Description("The CalendarRepairLogEnabled parameter specifies whether the Calendar Repair Attendant logs items that it repairs. The repair log doesn't contain failed repair attempts.")] Boolean CalendarRepairLogEnabled;
    [Write, Description("The CalendarRepairLogFileAgeLimit parameter specifies how long to retain calendar repair logs. Log files that exceed the maximum retention period are deleted.")] String CalendarRepairLogFileAgeLimit;
    [Write, Description("The CalendarRepairLogPath parameter specifies the location of the calendar repair log files on the Mailbox server.")] String CalendarRepairLogPath;
    [Write, Description("The CalendarRepairLogSubjectLoggingEnabled parameter specifies that the subject of the repaired calendar item is logged in the calendar repair log.")] Boolean CalendarRepairLogSubjectLoggingEnabled;
    [Write, Description("The CalendarRepairMissingItemFixDisabled parameter specifies that the Calendar Repair Assistant won't fix missing attendee calendar items for mailboxes homed on this Mailbox server.")] Boolean CalendarRepairMissingItemFixDisabled;
    [Write, Description("The CalendarRepairMode parameter specifies the mode that the Calendar Repair Assistant will run in."), ValueMap{"ValidateOnly","RepairAndValidate"}, Values{"ValidateOnly","RepairAndValidate"}] String CalendarRepairMode;
    [Write, Description("The CalendarRepairWorkCycle parameter specifies the time span in which all mailboxes on the specified server will be scanned by the Calendar Repair Assistant. Calendars that have inconsistencies will be flagged and repaired according to the interval specified by the CalendarRepairWorkCycleCheckpoint parameter.")] String CalendarRepairWorkCycle;
    [Write, Description("The CalendarRepairWorkCycleCheckpoint parameter specifies the time span at which all mailboxes will be identified as needing work completed on them.")] String CalendarRepairWorkCycleCheckpoint;
    [Write, Description("The DomainController parameter specifies the fully qualified domain name (FQDN) of the domain controller that writes this configuration change to Active Directory.")] String DomainController;
    [Write, Description("The DatabaseCopyActivationDisabledAndMoveNow parameter specifies whether to prevent databases from being mounted on this Mailbox server if there are other healthy copies of the databases on other Mailbox servers. It will also immediately move any mounted databases on the server to other servers if copies exist and are healthy.")] Boolean DatabaseCopyActivationDisabledAndMoveNow;
    [Write, Description("The DatabaseCopyAutoActivationPolicy parameter specifies the type of automatic activation available for mailbox database copies on the specified Mailbox server. Valid values are Blocked, IntrasiteOnly, and Unrestricted."), ValueMap{"Blocked","IntrasiteOnly","Unrestricted"}, Values{"Blocked","IntrasiteOnly","Unrestricted"}] String DatabaseCopyAutoActivationPolicy;
    [Write, Description("The FolderLogForManagedFoldersEnabled parameter specifies whether the folder log for managed folders is enabled for messages that were moved to managed folders.")] Boolean FolderLogForManagedFoldersEnabled;
    [Write, Description("The ForceGroupMetricsGeneration parameter specifies that group metrics information must be generated on the Mailbox server regardless of whether that server generates an offline address book (OAB). By default, group metrics are generated only on servers that generate OABs. Group metrics information is used by MailTips to inform senders about how many recipients their messages will be sent to. You need to use this parameter if your organization doesn't generate OABs and you want the group metrics data to be available.")] Boolean ForceGroupMetricsGeneration;
    [Write, Description("The IsExcludedFromProvisioning parameter specifies that the Mailbox server isn't considered by the OAB provisioning load balancer. If the IsExcludedFromProvisioning parameter is set to $true, the server won't be used for provisioning a new OAB or for moving existing OABs.")] Boolean IsExcludedFromProvisioning;
    [Write, Description("The JournalingLogForManagedFoldersEnabled parameter specifies whether the log for managed folders is enabled for journaling. The two possible values for this parameter are $true or $false. If you specify $true, information about messages that were journaled is logged. The logs are located at the location you specify with the LogPathForManagedFolders parameter.")] Boolean JournalingLogForManagedFoldersEnabled;
    [Write, Description("The Locale parameter specifies the locale. A locale is a collection of language-related user preferences such as writing system, calendar, and date format.")] String Locale [];
    [Write, Description("The LogDirectorySizeLimitForManagedFolders parameter specifies the size limit for all managed folder log files from a single message database. After the limit is reached for a set of managed folder log files from a message database, the oldest files are deleted to make space for new files.")] String LogDirectorySizeLimitForManagedFolders;
    [Write, Description("The LogFileAgeLimitForManagedFolders parameter specifies how long to retain managed folder logs. Log files that exceed the maximum retention period are deleted.")] String LogFileAgeLimitForManagedFolders;
    [Write, Description("The LogFileSizeLimitForManagedFolders parameter specifies the maximum size for each managed folder log file. When the log file size limit is reached, a new log file is created.")] String LogFileSizeLimitForManagedFolders;
    [Write, Description("The LogPathForManagedFolders parameter specifies the path to the directory that stores the managed folder log files.")] String LogPathForManagedFolders;
    [Write, Description("The MailboxProcessorWorkCycle parameter specifies how often to scan for locked mailboxes.")] String MailboxProcessorWorkCycle;
    [Write, Description("The ManagedFolderAssistantSchedule parameter specifies the intervals each week during which the Managed Folder Assistant applies messaging records management (MRM) settings to managed folders. The format is StartDay.Time-EndDay.")] String ManagedFolderAssistantSchedule[];
    [Write, Description("The ManagedFolderWorkCycle parameter specifies the time span in which all mailboxes on the specified server will be processed by the Managed Folder Assistant. The Managed Folder Assistant applies retention policies according to the ManagedFolderWorkCycleCheckpoint interval.")] String ManagedFolderWorkCycle;
    [Write, Description("The ManagedFolderWorkCycleCheckpoint parameter specifies the time span at which to refresh the list of mailboxes so that new mailboxes that have been created or moved will be part of the work queue. Also, as mailboxes are prioritized, existing mailboxes that haven't been successfully processed for a long time will be placed higher in the queue and will have a greater chance of being processed again in the same work cycle.")] String ManagedFolderWorkCycleCheckpoint;
    [Write, Description("The MAPIEncryptionRequired parameter specifies whether Exchange blocks MAPI clients that don't use encrypted remote procedure calls (RPCs).")] Boolean MAPIEncryptionRequired;
    [Write, Description("The MaximumActiveDatabases parameter specifies the number of databases that can be mounted on this Mailbox server. This parameter accepts numeric values.")] String MaximumActiveDatabases;
    [Write, Description("The MaximumPreferredActiveDatabases parameter specifies a preferred maximum number of databases that a server should have. This value is different from the actual maximum, which is configured using the MaximumActiveDatabases parameter. The value of MaximumPreferredActiveDatabases is only honored during best copy and server selection, database and server switchovers, and when rebalancing the DAG.")] String MaximumPreferredActiveDatabases;
    [Write, Description("The OABGeneratorWorkCycle parameter specifies the time span in which the OAB generation on the specified server will be processed.")] String OABGeneratorWorkCycle;
    [Write, Description("The OABGeneratorWorkCycleCheckpoint parameter specifies the time span at which to run OAB generation.")] String OABGeneratorWorkCycleCheckpoint;
    [Write, Description("The PublicFolderWorkCycle parameter is used by the public folder assistant to determine how often the mailboxes in a database are processed by the assistant.")] String PublicFolderWorkCycle;
    [Write, Description("The PublicFolderWorkCycleCheckpoint determines how often the mailbox list for a database is evaluated. The processing speed is also calculated.")] String PublicFolderWorkCycleCheckpoint;
    [Write, Description("The RetentionLogForManagedFoldersEnabled parameter specifies whether the Managed Folder Assistant logs information about messages that have reached their retention limits.")] Boolean RetentionLogForManagedFoldersEnabled;
    [Write, Description("The SharingPolicySchedule parameter specifies the intervals each week during which the sharing policy runs. The Sharing Policy Assistant checks permissions on shared calendar items and contact folders in users' mailboxes against the assigned sharing policy. The assistant lowers or removes permissions according to the policy. The format is StartDay.Time-EndDay.Time.")] String SharingPolicySchedule[];
    [Write, Description("The SharingPolicyWorkCycle parameter specifies the time span in which all mailboxes on the specified server will be scanned by the Sharing Policy Assistant. The Sharing Policy Assistant scans all mailboxes and enables or disables sharing polices according to the interval specified by the SharingPolicyWorkCycle.")] String SharingPolicyWorkCycle;
    [Write, Description("The SharingPolicyWorkCycleCheckpoint parameter specifies the time span at which to refresh the list of mailboxes so that new mailboxes that have been created or moved will be part of the work queue. Also, as mailboxes are prioritized, existing mailboxes that haven't been successfully processed for a long time will be placed higher in the queue and will have a greater chance of being processed again in the same work cycle.")] String SharingPolicyWorkCycleCheckpoint;
    [Write, Description("The SharingSyncWorkCycle parameter specifies the time span in which all mailboxes on the specified server will be synced to the cloud-based service by the Sharing Sync Assistant. Mailboxes that require syncing will be synced according to the interval specified by the SharingSyncWorkCycleCheckpoint parameter.")] String SharingSyncWorkCycle;
    [Write, Description("The SharingSyncWorkCycleCheckpoint parameter specifies the time span at which to refresh the list of mailboxes so that new mailboxes that have been created or moved will be part of the work queue. Also, as mailboxes are prioritized, existing mailboxes that haven't been successfully processed for a long time will be placed higher in the queue and will have a greater chance of being processed again in the same work cycle.")] String SharingSyncWorkCycleCheckpoint;
    [Write, Description("The SiteMailboxWorkCycle parameter specifies the time span in which the site mailbox information on the specified server will be processed.")] String SiteMailboxWorkCycle;
    [Write, Description("The SiteMailboxWorkCycleCheckpoint parameter specifies the time span at which to refresh the site mailbox workcycle.")] String SiteMailboxWorkCycleCheckpoint;
    [Write, Description("The SubjectLogForManagedFoldersEnabled parameter specifies whether the subject of messages is displayed in managed folder logs.")] Boolean SubjectLogForManagedFoldersEnabled;
    [Write, Description("The TopNWorkCycle parameter specifies the time span in which all mailboxes that have Unified Messaging on the specified server will be scanned by the TopN Words Assistant. The TopN Words Assistant scans voice mail for the most frequently used words to aid in transcription.")] String TopNWorkCycle;
    [Write, Description("The TopNWorkCycleCheckpoint parameter specifies the time span at which to refresh the list of mailboxes so that new mailboxes that have been created or moved will be part of the work queue. Also, as mailboxes are prioritized, existing mailboxes that haven't been successfully processed for a long time will be placed higher in the queue and will have a greater chance of being processed again in the same work cycle.")] String TopNWorkCycleCheckpoint;
    [Write, Description("The UMReportingWorkCycle parameter specifies the time span in which the arbitration mailbox named SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9} on the specified server will be scanned by the Unified Messaging Reporting Assistant. The Unified Messaging Reporting Assistant updates the Call Statistics reports by reading Unified Messaging call data records for an organization on a regular basis.")] String UMReportingWorkCycle;
    [Write, Description("The UMReportingWorkCycleCheckpoint parameter specifies the time span at which the arbitration mailbox named SystemMailbox{e0dc1c29-89c3-4034-b678-e6c29d823ed9} will be marked by processing.")] String UMReportingWorkCycleCheckpoint;
    [Write, Description("The WacDiscoveryEndpoint parameter specifies the Office Online Server endpoint to use. Exchange 2016 only.")] String WacDiscoveryEndpoint;
};

