
[ClassVersion("1.0.0.0"), FriendlyName("xExchWaitForADPrep")]
class MSFT_xExchWaitForADPrep : OMI_BaseResource
{
    [Key, Description("Not actually used. Enter anything, as long as it's not null")] String Identity;
    [Write, Description("Credentials used to perform Active Directory lookups against the Schema, Configuration, and Domain naming contexts"), EmbeddedInstance("MSFT_Credential")] String Credential;

    //To find appropriate values for the next three properties, consult the 'Exchange 2013 Active Directory versions' setion
    //of the following article:
    //Prepare Active Directory and domains
    //http://technet.microsoft.com/en-us/library/bb125224(v=exchg.150).aspx
    [Write, Description("Specifies that the Active Directory schema should have been prepared using Exchange 2013 'setup /PrepareSchema', and should be at the specified version")] Sint32 SchemaVersion;
    [Write, Description("Specifies that the Exchange Organization should have been prepared using Exchange 2013 'setup /PrepareAD', and should be at the specified version")] Sint32 OrganizationVersion;
    [Write, Description("Specifies that the domain containing the target Exchange 2013 server was prepared using setup /PrepareAD, /PrepareDomain, or /PrepareAllDomains, and should be at the specified version")] Sint32 DomainVersion;

    [Write, Description("The FQDN's of domains that should be checked for DomainVersion in addition to the domain that this Exchange server belongs to")] String ExchangeDomains[];
    [Write, Description("How many seconds to wait between retries when checking whether AD has been prepped. Defaults to 60.")] Uint32 RetryIntervalSec;
    [Write, Description("How many retry attempts should be made to see if AD has been prepped before an exception is thrown. Defaults to 30.")] Uint32 RetryCount;
};

